### ISSUE TITLE
No settings.js file on port 9999

### ISSUE THREAD

**Issue by MrHalfman** [jonashagstedt/swampdragon#15]
Hi, sorry if it's a dumb question but I can't get the settings.js file.

I didn't found anything in the documentation that mention where we can get this file. The url "http://my-domain.com:9999/settings.js" returns nothing.

I'm running my Django Project on an Nginx Server with uWSGI.

Thanks for the answer.

**Comment by MrHalfman** [comment]
After many search I found what I wanted in this blog post : http://swampdragon.net/blog/deploying-swampdragon/

You should really integrate this into the documentation :wink:.

**Comment by MrHalfman** [comment]
With some changes I succedeed in talking to the server.

Now I have an error :
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1332, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/swampdragon/settings_provider.py", line 14, in get
    'host': self.request.headers['Host'],
  File "/usr/local/lib/python2.7/dist-packages/tornado/httputil.py", line 209, in __getitem__
    return dict.__getitem__(self, _normalized_headers[name])
KeyError: 'Host'
```

**Comment by MrHalfman** [comment]
I've made a mistake in the nginx config file >_<. Sorry again and keep the awesome work.

**Comment by jonashagstedt** [comment]
I might make the deployment process into a tutorial rather than a blog post.
Deployment depends a lot on the individual. Personally I like uWSGI and NGINX, however some people prefer gunicorn instead, and I don't want to give the impression that people have to use uWSGI.

I will release an update soon, which will get rid of `localhost:9999/settings.js` in favour of using a template tag instead, this way it won't be necessary to go through the process of creating a custom context processor for different environments as well (it will all be managed through your settings.py).

Happy to see that you solved your issue
