### ISSUE TITLE
Tutorial Issues

### ISSUE THREAD

**Issue by cancan101** [jonashagstedt/swampdragon#18]
This for Django 1.7:
```
# Django >= 1.7
./manage.py migrate
./manage.py createsuperuser
```

is missing `./manage.py makemigrations todo` (see: https://docs.djangoproject.com/en/1.7/intro/tutorial01/#activating-models).

Also there is no mention in the tutorial about getting `server.py`. It just says to run the script.
See either [this](http://swampdragon.net/documentation/adding-swampdragon-to-an-existing-django-project/) or #17.

Tutorial should also mention that you need to launch `redis-server`.

**Comment by jonashagstedt** [comment]
Which tutorial is this for?

If memory serves me I have tested all tutorials with both python 2.7 and 3.4, and Django 1.6 and 1.7.
The way I test them is simply copy and paste everything from the tutorial following the instructions to the point (I've also had other people testing them).

If we are talking about this tutorial: http://swampdragon.net/tutorial/part-1-here-be-dragons-and-thats-a-good-thing/ (the todo app) then this line: `dragon-admin startproject tutorial` will create the server.py file.

I have added `./manage.py makemigrations todo` in there now though.

**Comment by cancan101** [comment]
RE: `dragon-admin startproject tutorial`, the tutorial says this:

>Creating a project
Start by creating a project. There is a shortcut to creating a project. Run the following command:

>dragon-admin startproject tutorial
This does the same as django-admin startproject with the addition of adding

># SwampDragon settings
SWAMP_DRAGON_CONNECTION = ('swampdragon.connections.sockjs_connection.DjangoSubscriberConnection', '/data')
to you settings file, along with adding swampdragon to your installed apps:

>INSTALLED_APPS = (
    ...
    'swampdragon',
)
You should now have a project structure that looks like this:

>tutorial/
    manage.py
    tutorial/
        __init__.py
        settings.py
        urls.py
        wsgi.py

There is no mention of server.py in the directory structure shown or in the list of steps performed. Since I did not use the command but followed what the tutorial said the start script did, I did not end up with the `server.py`.

**Comment by cancan101** [comment]
Also one question about the code in the JS controller:
```
        $dragon.subscribe('todo-item', $scope.channel, {todo_list__id: 1}).then(function(response) {
            $scope.dataMapper = new DataMapper(response.data);
        });
```
and
```
        $dragon.getList('todo-item', {list_id:1}).then(function(response) {
            $scope.todoItems = response.data;
        });
```

The first uses a filter: `{todo_list__id: 1}` and the second `{list_id:1}`. Why the difference?

You even call out the safety benefits of the second approach in the docs:
>it's never a good idea to simply trust what the client sends us!

yet it seems like in the first case you ARE trusting the user.

**Comment by jonashagstedt** [comment]
Right you are. I've updated the tutorial. I am omitting the requirement to edit the server.py file as it's not part of the tutorial. If you do this manually you need to change <project> to the name of your project (similar to how you would have to update your manage.py if you renamed your project, to find the settings file)

**Comment by cancan101** [comment]
I really think #17 is the way to deal with server and server.py should just be eliminated. As far as redis,
 I do like the idea of having the tutorial as self contained as possible. I know that I was a little confused at first about since I did not realize that I had to start redis.

**Comment by jonashagstedt** [comment]
The first case of `{todo_list__id: 1}` could be a security issue. This is creating the subscription, and in short is saying "subscribe to all to-do items that belongs to the to-do list with an id of one.

You could effectively subscribe to any list doing this.
My comment is rather general "don't trust what the user sends".

This tutorial is already in two parts and is a way to get people started with SD. If I am too specific on every aspect the tutorial would become way to long, and I need to keep it concise and as short as possible.

For more information about filtering what is subscribed on check out: http://swampdragon.net/documentation/routers/ under **Subscribing to a channel**

I'll admit that the documentation is a bit sparse as well

**Comment by jonashagstedt** [comment]
I haven't had a chance to review your PR yet but I really do like the idea of having it as a management command.

I will most likely keep the server.py there however, since I've written about it in a post about deployment and I currently use it my self in various projects so removing server.py would break for some.

I think `server` is too general however, so might rename the command (it might get confused with run_server). I have this weekend put aside for starting with the DRF serializer integration and I will review the PR as well if time permits

**Comment by cancan101** [comment]
I understand not doing everything in the tutorial but I think you make a good point in the tutorial about not trusting user input. Since you already show the "right" way to not trust user input in the `getList ` call, it seems that for consistency it would be great if you did it at subscribe time as well.

How would you do this in the subscribe call?

**Comment by cancan101** [comment]
"eliminated" was too strong a word. Phased-out or deprecated or a at least no longer recommended would be better ways of saying it.

Sure, 'server' is too vague. Perhaps `swamp-server` or something like that.

**Comment by jonashagstedt** [comment]
The safe way of doing it would be to not include the list id at all in the subscribe call.

So changing the JS that does the subscription to this:

        $dragon.subscribe('todo-item', $scope.channel, {list_id: 1}).then(function(response) {
            $scope.dataMapper = new DataMapper(response.data);
        });

This will pass on `list_id:1` to the router which will be available in `get_subscription_context`.

Then in the todo list item router you could add the following:

    def get_subscription_contexts(self, **kwargs):
        return {'todo_list__id': kwargs['list_id']}

(note: calling it `list_id` is not a requirement, it could be called anything, it's just a variable name).

You could also ignore the entire argument and hard code the list id:

    def get_subscription_contexts(self, **kwargs):
        return {'todo_list__id': 1}

As an additional note: the subscription context filtering is pretty basic in comparison to Django's ORM filtering. It supports some of the operations like _lt, _lte, _gte etc. however if you need to do some advanced filtering before publishing the data it would be better to create generic channels and do the filtering and publishing elsewhere.

So for instance you want to publish all todo items where the id is between 1 and 100, OR the list name starts with the word foo (a rather obscure example) then `get_subscription_context` wouldn't work since it doesn't know about `or` (at the time of writing this at least).

In that scenario you could setup a signal for when the TodoItem is saved (or it won't work from admin) and in that signal:

	from swampdragon.pubsub_providers.data_publisher import publish_data

	if (todo_item.id >= 1 and todo_item.id <= 100) or todo_item.list.title.startswith('foo'):
		serialized_todo_item = todo_item.serialize()
		publish_data('public_channel', serialized_todo_item)

This assumes that the name of the channel the user is subscribed to is called `public_channel`

**Comment by cancan101** [comment]
It looks like this line in the tutorial is double mark-downed:
>\`\`\`$dragon.getSingle('todo-list', {id:1}).then(function(response){ ... });```

**Comment by jonashagstedt** [comment]
Doh! Good spot. 
Fixed it.

It's really great having a second pair of eyes on this. Thanks
