### ISSUE TITLE
How to remove callbacks added with onChannelMessage ?

### ISSUE THREAD

**Issue by NotSqrt** [jonashagstedt/swampdragon#33]
In a single page app, I need to clear the swampdragon connection:
 * I can unsubscribe from all the channels
 * but I can't empty what had been added to callbackQueue
 * if I resubscribe to a channel, I don't want the old functions previously added in onChannelMessage to be called again.

Any ideas ?

**Comment by jonashagstedt** [comment]
I can see how this is an issue. I'll look in to it.

**Comment by jonashagstedt** [comment]
Okay if you want to give this one a go:

    pip uninstall swampdragon
    pip install -e git+https://github.com/jonashagstedt/swampdragon.git@#egg=swampdragon

When you unsubscribe from a channel it should no longer linger.

**Comment by NotSqrt** [comment]
It does not seem to fix my problem, I suspect that callbacks are not removed from ``callbackQueue``.

my setup:

```javascript

function closureOnChannelMessage (closure) {

    return function (channels, message) {
          if (channels[0] === "queues") {
              // do stuff that requires the closure
          }
    }
}

var channel_callback = closureOnChannelMessage(this);
swampdragon.onChannelMessage(channel_callback);

swampdragon.open(function () {
    swampdragon.subscribe("celery", "queues", null);
});
```

later :


```javascript
swampdragon.unsubscribe("celery", "queues", null);
```
Even later :

```javascript
var channel_callback = closureOnChannelMessage(this);  // the closure changed, re-instanciate a callback
swampdragon.onChannelMessage(channel_callback);

swampdragon.open(function () {
    swampdragon.subscribe("celery", "queues", null);
});
```

The old instance ``channel_callback`` is called after resubscribing.


As you can see in my callback, I have to do `` if (channels[0] === "queues")`` to filter messages from other channels, since I have registered other callbacks with  ``swampdragon.onChannelMessage``.

(Is it the way to do it, when listening to multiple channels ?)

I would probably expect something like:

```javascript
// instead of calling swampdragon.onChannelMessage(channel_callback), pass callback when subscribing
swampdragon.subscribe(route, channel, args, success, failure, messageCallback);

// messageCallback gets registered in conjunction with channel, so that only these callbacks get called when a message is received

// when unsubscribing from a channel, we can say if we want all the callbacks attached to that channel to be clearer
swampdragon.unsubscribe(route, channel, deleteCallbacks:boolean);
```

**Comment by jonashagstedt** [comment]
Actually the way you do it is correct.

    // Subscribe to the celery router with my local channel named "queues"
    swampdragon.subscribe("celery", "queues");

    // Subscribe to the foo router with my local channel named "foos"
    swampdragon.subscribe("foo", "foos");


    swampdragon.onChannelMessage(function (channels, message) {
        for (var i = 0; i < channels.length; i += 1) {
            if (channels[i] == "queues") {
                handleQueueMessage(message)
            }
            if (channels[i] == "foos") {
                handleFooMessage(message)
            }
        }
    });


    function handleQueueMessage(message) {
        // handle message
    }

    function handleFooMessage(message) {
        // handle message
    }


If you then unsubscribe from "queues" you will no longer receive messages on that channel.

Channels are not as straight forward as you can have multiple remote sources mapping to the same local channel.

Imagine a scenario where you want to subscribe to public and private notifications.
So when a user subscribe we assign two channels that user listens to:

*  public_notifications
*  user_1_notifications (the users primary key is one)

From JavaScript you might call something like `swampdragon.subscribe("notification-router", "notifications");`.
The subscribe command will receive a callback with the channel setup, which will inform swampdragon that: both public_notifications and user_1_notifications maps to notifications.


**So why not `swampdragon.subscribe(route, channel, args, success, failure, messageCallback);`** ?

You couldn't simply write `swampdragon.subscribe(route, channel);` anymore (which is really not that good to do but it's convenient), but more importantly:

Since you can put `swampdragon.onChannelMessage(function (channels, message) { });` anywhere in your application you only need to subscribe once and you can listen to this event anywhere.

You could in effect have an application where you subscribe to users.

So let's say you have these two files:

users.js
notifications.js

and then in both you can do the following:

    // users.js
    swampdragon.onChannelMessage(function (channels, message) {
        // add a user to a list of something similar
    };


    // notifications.js
    swampdragon.onChannelMessage(function (channels, message) {

        if (channels[0] === "users") {
            // If the user was deleted, show a "user removed" notification
            // if it was a new user show a "new user" notifications
        }

        if (channels[0] === "other") {
            // Show other type of notifications
        }

    };


If we attached the channel message callback directly to the subscribe call then you wouldn't be able to look for these anywhere else in your application (well you could but you would have to create some kind of broadcast singletone guy that you call everything you receive a channel message).


Hope that makes sense

**Comment by NotSqrt** [comment]
Ok for not passing the callback to ``subscribe``.

What about modifying/deleting the callbacks previously registered through ``onChannelMessage`` ?

I am in a single page application, where a callback is only valid in a certain scope. If I leave this scope (page change), I need to clear the callbacks that are now irrelevant.

**Comment by jonashagstedt** [comment]
Right now there is no clear way to remove the onChannelMessage callback.

Since I am not sure how you handle your page states I'm proposing a solution based on guess here:

    var channelMessageCallbacks = {};


    function mapCallback(name, fn) {
         channelMessageCallbacks[name] = fn;
    }

    function unmapCallback(name) {
        del channelMessageCallbacks[name];
    }


    swampdragon.onChannelMessage(channels, message) {
        for (var name in channelMessageCallbacks) {
            channelMessageCallbacks[name](channels, message);
        }
    }


    var Page = function () {
        var _pagename = 'home';

        return {
            pageLoad: function() {
                var onChanMessage = function(channels, message) { ... }
                mapCallback(_pagename, onChanMessage);
            },

            pageUnload: function () {
                unmapCallback(_pagename);
            }
        }
    }

If you have any suggestions for improvements I am obviously interested.
Preferably without breaking backwards compatibility.

**Comment by NotSqrt** [comment]
Ok, I have adopted something similar (I just fixed the argument of ``onChannelMessage``)

```javascript
var channelMessageCallbacks = {};

function mapCallback(keyword, fn) {
	channelMessageCallbacks[keyword] = fn;
}

function unmapCallback(keyword) {
	delete channelMessageCallbacks[keyword];
}


// only 1 global call to ``swampdragon.onChannelMessage`` in the whole code
swampdragon.onChannelMessage(function (channels, message) {
	for (var keyword in channelMessageCallbacks) {
		channelMessageCallbacks[keyword](channels, message);
	}
});

// at page load
function callback(channels, message) {};
mapCallback("page_keyword", callback);

// at page unload
unmapCallback("page_keyword");
```

The only limit to keep in mind is that there is only 1 callback per keyword (it's obviously possible to convert this into a list of callbacks).
