### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by leesolway** [jonashagstedt/swampdragon#66]
Would it be possible to have an idea of your intentions with the project. Is Swam Dragon being actively developed and maintained, is their a roadmap and can people contribute to that roadmap and development?

Background: I am currently assessing Swamp Dragon for a big project. So far i really like the direction and i am interested to see where it is going.

**Comment by jonashagstedt** [comment]
It is being actively developed and maintained.
I'm working on the 0.4.2 branch at the moment, bring Django 1.8 compatibility along with a few changes to testing.

There isn't really a roadmap but it could benefit from one.

One of the bigger changes to do is to make it compatible with DRF serializers but that is not a small feat, but if there was a roadmap that would certainly be on it.

I am happy for people to contribute as long as they write tests for the changes, assuming you can test the changes (documentation changes etc. can of course not be tested).

I started this project because there was nothing out there that let me do things in this way, using routers, working with Django models etc.

If you have any suggestions and want to contribute I am more than happy to chat about it.

The biggest things right now (on the non-existing roadmap) are:
*  Django 1.8 compatibility
*  DRF serializers
*  Optimise the way self publishing models work

**Comment by jonashagstedt** [comment]
I'm closing this down for now but feel free to contact me with ideas for enhancements or pull requests if you want to
