### ISSUE TITLE
Since 0.4.2 SelfPublishModel does not detect changes to ForeignKeys

### ISSUE THREAD

**Issue by Gromph** [jonashagstedt/swampdragon#76]
It looks like fix for Issue #52 removed ForeignKeys from relevant_fields, but it did not substitute in the raw _id field. So SelfPublishModel does not detect changes to ForeignKey fields. This is something that we need in our app. The fix in the comments of Issue #52 does still work for us.

**Comment by jonashagstedt** [comment]
Writing a test for this now and doing a fix

**Comment by jonashagstedt** [comment]
Could you elaborate a bit more on this. 
If you only check the related id, how can a change on a related model be detected?

I wrote the following test case now, using 0.4.2:

https://gist.github.com/jonashagstedt/86fa8cc442d1a1d5b8bf

And it does detect changes in the related model.

Could you write a test case that would work with your suggested code and doesn't work with the current 0.4.2. If I can see exactly where the issue is I can review the code again.

**Comment by Gromph** [comment]
I currently don't need to know about changes in the related model, I need to know when changes happen to which model the ForeignKey is referencing. Meaning changes to the ForeignKey field itself.

**Comment by jonashagstedt** [comment]
E.g changing the reference?
So if you have 

Foo_a -> Bar_a and then change bar_id of Foo_a to Bar_b?

**Comment by Gromph** [comment]
ya

**Comment by jonashagstedt** [comment]
Okay I need to ponder this for a bit. I believe you are right that the change should be published

**Comment by jonashagstedt** [comment]
fixed and on pypi as 0.4.2.1
